<?php
// install SMTP Authentication Support
// go the config SMTP -> turn on full 
// SMTP sever : smtp.gmail.com; SMTP port: 465
// SMTP authentication user: "admin@example" pass "123abc"

function modal_menu() {
    $items = array();
  
    $items['modal_form'] = array( //this creates a URL that will call this form at "examples/form-example"
      'title' => 'Modal Form', //page title
      'description' => 'A form to mess around with.',
      'page callback' => 'drupal_get_form', //this is the function that will be called when the page is accessed.  for a form, use drupal_get_form
      'page arguments' => array('modal_form'), //put the name of the form here
      'access arguments' => array('administer users'),

    );
    return $items;
  }



function modal_form($form, &$formstate){


    $form['subject'] = array(
        '#type' => 'textfield',
        '#title' => 'Subject',
        '#required' => TRUE,
        '#default_value' => variable_get('subject', ''),
    );

    $form['email_body'] = array(
        '#type' => 'textarea',
        '#title' => 'Email Body',
        '#required' => TRUE,
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Submit'),
    );
   
    return $form;    
}



function modal_form_validate($form, &$form_state) {


}


function modal_mail ($key, &$message, $params) {

    switch ($key) {
      case 'modal_email':
        $message['subject'] = t('@subject',array('@subject' =>$params['subject']));
        $message['body'][] = t('Hello @email_body,', array('@email_body' => $params['email_body']));
          
        break;
    }
}

function modal_form_submit($form, &$form_state) {

    $subject = $form_state['values']['subject'];
    $email_body = $form_state['values']['email_body'];
    drupal_set_message($subject);    
    $params = array(
        'subject' => $subject,
        'email_body' => $email_body,
    );

    $module ='modal';
    $key ='modal_email';
    $to ='';   
    // drupal_mail($module, $key, $to, $language, $params = array('username' => 'John Potato'), $from = NULL, $send = TRUE);
    $var = entity_load('user');
    foreach($var as $items){
        foreach($items->roles as $item){
            if($item == 'authenticated user'){
                $to = $items->init;
                drupal_mail($module,$key,$to,language_default(), $params);

            }
        }
    }

}



